feat: Move applications to fluxcd repo

diff --git a/hack/secret b/hack/secret
--- a/hack/secret
+++ b/hack/secret
@@ -1,6 +1,8 @@
 #!/bin/sh
-set -ex
+set -e
 for f in $(find -type f -name secret.yml);
 do
-	kubectl apply -f $f;
+    echo "\n->->->-> $f ..."
+	kubectl apply -f $f || echo "->->->-> $f failed" && continue
+    echo "->->->-> $f ok!"
 done
